### ISSUE TITLE
Wirframe & Lo-Fi

### ISSUE THREAD

**Issue by draycodes** [zuri-training/anima_lib_team99#26]
Done by Kenechukwu , Nenye and Pamela

**Comment by Goddessximena** [comment]
Arrange, Organise the design of the wireframe and lo-fi pages.
Landing Page
Documentation Page
SignIn/SignUp/Authentication Page
Download page
Dashboard
Forum

**Comment by nudsgnr** [comment]
Made final corrections to each designed page.
